version: '3.8'

services:

  postgres:
    image: postgres:13
    environment:
      PGUSER: julien
      PGPASSWORD: password
      POSTGRES_USER: julien
      POSTGRES_PASSWORD: password
    volumes:
      - ./data-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_USER=julien
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db-dev
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - ./backend:/usr/src/
